### ISSUE TITLE
Bulk consume is not working with new parameter - without-last-modified

### ISSUE THREAD

**Issue by yanpom** [CM-Well/CM-Well#1059]
No answer received when bulk consume data with without-last-modified parameter
Following exception appear in bg log:
```
2019-02-18 10:36:50,364 -well-lndn-akka.actor.default-dispatcher-50] ERROR cmwell.bg.CMWellBGActor              - Crawler [persist_topic, partition: 1] finished with exception. Sending a self message to mark it as finished. The exception was:
org.elasticsearch.transport.RemoteTransportException: [192.168.130.4][inet[/192.168.130.4:9304]][indices:data/read/get]
Caused by: org.elasticsearch.transport.RemoteTransportException: [192.168.130.11][inet[/192.168.130.11:9303]][indices:data/read/get[s]]
Caused by: org.elasticsearch.ElasticsearchParseException: failed to parse / load source
        at org.elasticsearch.search.lookup.SourceLookup.loadSourceIfNeeded(SourceLookup.java:81)
        at org.elasticsearch.search.lookup.SourceLookup.extractRawValues(SourceLookup.java:145)
        at org.elasticsearch.index.get.ShardGetService.innerGetLoadFromStoredFields(ShardGetService.java:378)
        at org.elasticsearch.index.get.ShardGetService.innerGet(ShardGetService.java:210)
        at org.elasticsearch.index.get.ShardGetService.get(ShardGetService.java:104)
        at org.elasticsearch.action.get.TransportGetAction.shardOperation(TransportGetAction.java:104)
        at org.elasticsearch.action.get.TransportGetAction.shardOperation(TransportGetAction.java:44)
        at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$ShardTransportHandler.messageReceived(TransportShardSingleOperationAction.java:297)
        at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$ShardTransportHandler.messageReceived(TransportShardSingleOperationAction.java:280)
        at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:279)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.elasticsearch.ElasticsearchIllegalStateException: No matching token for number_type [BIG_INTEGER]
        at org.elasticsearch.common.xcontent.json.JsonXContentParser.convertNumberType(JsonXContentParser.java:207)
        at org.elasticsearch.common.xcontent.json.JsonXContentParser.numberType(JsonXContentParser.java:66)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:295)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readList(AbstractXContentParser.java:284)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:310)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:275)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:308)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:275)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:308)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:275)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:254)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.map(AbstractXContentParser.java:208)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.mapAndClose(AbstractXContentParser.java:219)
        at org.elasticsearch.common.xcontent.XContentHelper.convertToMap(XContentHelper.java:127)
        at org.elasticsearch.common.xcontent.XContentHelper.convertToMap(XContentHelper.java:81)
        at org.elasticsearch.search.lookup.SourceLookup.sourceAsMapAndType(SourceLookup.java:87)
        at org.elasticsearch.search.lookup.SourceLookup.loadSourceIfNeeded(SourceLookup.java:76)
        ... 13 common frames omitted
2019-02-18 10:36:50,364 -well-lndn-akka.actor.default-dispatcher-65] INFO  cmwell.bg.CMWellBGActor              - Crawler [persist_topic, partition: 1] stopped. Check its logs for details. Marking it as stopped and restarting it in 30000 milliseconds
2019-02-18 10:37:20,383 -well-lndn-akka.actor.default-dispatcher-46] INFO  cmwell.bg.CMWellBGActor              - starting Crawler [persist_topic, partition: 1]
2019-02-18 10:37:20,388 -well-lndn-akka.kafka.default-dispatcher-31] INFO  o.a.k.c.consumer.ConsumerConfig      - ConsumerConfig values:
        auto.commit.interval.ms = 5000
        auto.offset.reset = earliest
        bootstrap.servers = [localhost:9092]
        check.crcs = true
        client.id =
        connections.max.idle.ms = 540000
        enable.auto.commit = false
        exclude.internal.topics = true
        fetch.max.bytes = 52428800
        fetch.max.wait.ms = 500
        fetch.min.bytes = 1
        group.id =
        heartbeat.interval.ms = 3000
        interceptor.classes = null
        key.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
        max.partition.fetch.bytes = 1048576
        max.poll.interval.ms = 300000
        max.poll.records = 500
        metadata.max.age.ms = 300000
        metric.reporters = []
        metrics.num.samples = 2
        metrics.recording.level = INFO
        metrics.sample.window.ms = 30000
        partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
        receive.buffer.bytes = 65536
        reconnect.backoff.ms = 50
        request.timeout.ms = 305000
        retry.backoff.ms = 100
        sasl.jaas.config = null
        sasl.kerberos.kinit.cmd = /usr/bin/kinit
        sasl.kerberos.min.time.before.relogin = 60000
        sasl.kerberos.service.name = null
        sasl.kerberos.ticket.renew.jitter = 0.05
        sasl.kerberos.ticket.renew.window.factor = 0.8
        sasl.mechanism = GSSAPI
        security.protocol = PLAINTEXT
        send.buffer.bytes = 131072
        session.timeout.ms = 10000
        ssl.cipher.suites = null
        ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
        ssl.endpoint.identification.algorithm = null
        ssl.key.password = null
        ssl.keymanager.algorithm = SunX509
        ssl.keystore.location = null
        ssl.keystore.password = null
        ssl.keystore.type = JKS
        ssl.protocol = TLS
        ssl.provider = null
        ssl.secure.random.implementation = null
        ssl.trustmanager.algorithm = PKIX
        ssl.truststore.location = null
        ssl.truststore.password = null
        ssl.truststore.type = JKS
        value.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer

2019-02-18 10:37:20,389 -well-lndn-akka.kafka.default-dispatcher-31] INFO  o.a.kafka.common.utils.AppInfoParser - Kafka version : 0.10.2.1
2019-02-18 10:37:20,389 -well-lndn-akka.kafka.default-dispatcher-31] INFO  o.a.kafka.common.utils.AppInfoParser - Kafka commitId : e89bffd6b2eff799
2019-02-18 10:37:20,412 [elasticsearch[Aralune][listener][T#9]]      ERROR cmwell.fts.FTSServiceNew             - Exception from ElasticSearch (no timeout, response returned in [13ms])
org.elasticsearch.transport.RemoteTransportException: [192.168.130.16][inet[/192.168.130.16:9304]][indices:data/read/get]
Caused by: org.elasticsearch.transport.RemoteTransportException: [192.168.130.11][inet[/192.168.130.11:9303]][indices:data/read/get[s]]
Caused by: org.elasticsearch.ElasticsearchParseException: failed to parse / load source
        at org.elasticsearch.search.lookup.SourceLookup.loadSourceIfNeeded(SourceLookup.java:81)
        at org.elasticsearch.search.lookup.SourceLookup.extractRawValues(SourceLookup.java:145)
        at org.elasticsearch.index.get.ShardGetService.innerGetLoadFromStoredFields(ShardGetService.java:378)
        at org.elasticsearch.index.get.ShardGetService.innerGet(ShardGetService.java:210)
        at org.elasticsearch.index.get.ShardGetService.get(ShardGetService.java:104)
        at org.elasticsearch.action.get.TransportGetAction.shardOperation(TransportGetAction.java:104)
        at org.elasticsearch.action.get.TransportGetAction.shardOperation(TransportGetAction.java:44)
        at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$ShardTransportHandler.messageReceived(TransportShardSingleOperationAction.java:297)
        at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$ShardTransportHandler.messageReceived(TransportShardSingleOperationAction.java:280)
        at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:279)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.elasticsearch.ElasticsearchIllegalStateException: No matching token for number_type [BIG_INTEGER]
        at org.elasticsearch.common.xcontent.json.JsonXContentParser.convertNumberType(JsonXContentParser.java:207)
        at org.elasticsearch.common.xcontent.json.JsonXContentParser.numberType(JsonXContentParser.java:66)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:295)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readList(AbstractXContentParser.java:284)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:310)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:275)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:308)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:275)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:308)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:275)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:254)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.map(AbstractXContentParser.java:208)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.mapAndClose(AbstractXContentParser.java:219)
        at org.elasticsearch.common.xcontent.XContentHelper.convertToMap(XContentHelper.java:127)
        at org.elasticsearch.common.xcontent.XContentHelper.convertToMap(XContentHelper.java:81)
        at org.elasticsearch.search.lookup.SourceLookup.sourceAsMapAndType(SourceLookup.java:87)
        at org.elasticsearch.search.lookup.SourceLookup.loadSourceIfNeeded(SourceLookup.java:76)
        ... 13 common frames omitted
2019-02-18 10:37:20,413 -well-lndn-akka.actor.default-dispatcher-29] ERROR cmwell.bg.CMWellBGActor              - Crawler [persist_topic, partition: 1] finished with exception. Sending a self message to mark it as finished. The exception was:
org.elasticsearch.transport.RemoteTransportException: [192.168.130.16][inet[/192.168.130.16:9304]][indices:data/read/get]
Caused by: org.elasticsearch.transport.RemoteTransportException: [192.168.130.11][inet[/192.168.130.11:9303]][indices:data/read/get[s]]
Caused by: org.elasticsearch.ElasticsearchParseException: failed to parse / load source
        at org.elasticsearch.search.lookup.SourceLookup.loadSourceIfNeeded(SourceLookup.java:81)
        at org.elasticsearch.search.lookup.SourceLookup.extractRawValues(SourceLookup.java:145)
        at org.elasticsearch.index.get.ShardGetService.innerGetLoadFromStoredFields(ShardGetService.java:378)
        at org.elasticsearch.index.get.ShardGetService.innerGet(ShardGetService.java:210)
        at org.elasticsearch.index.get.ShardGetService.get(ShardGetService.java:104)
        at org.elasticsearch.action.get.TransportGetAction.shardOperation(TransportGetAction.java:104)
        at org.elasticsearch.action.get.TransportGetAction.shardOperation(TransportGetAction.java:44)
        at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$ShardTransportHandler.messageReceived(TransportShardSingleOperationAction.java:297)
        at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$ShardTransportHandler.messageReceived(TransportShardSingleOperationAction.java:280)
        at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:279)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.elasticsearch.ElasticsearchIllegalStateException: No matching token for number_type [BIG_INTEGER]
        at org.elasticsearch.common.xcontent.json.JsonXContentParser.convertNumberType(JsonXContentParser.java:207)
        at org.elasticsearch.common.xcontent.json.JsonXContentParser.numberType(JsonXContentParser.java:66)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:295)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readList(AbstractXContentParser.java:284)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:310)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:275)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:308)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:275)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:308)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:275)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:254)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.map(AbstractXContentParser.java:208)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.mapAndClose(AbstractXContentParser.java:219)
        at org.elasticsearch.common.xcontent.XContentHelper.convertToMap(XContentHelper.java:127)
        at org.elasticsearch.common.xcontent.XContentHelper.convertToMap(XContentHelper.java:81)
        at org.elasticsearch.search.lookup.SourceLookup.sourceAsMapAndType(SourceLookup.java:87)
        at org.elasticsearch.search.lookup.SourceLookup.loadSourceIfNeeded(SourceLookup.java:76)
        ... 13 common frames omitted
```

**Comment by bryaakov** [comment]
@e-orz do we need this item fixed?

**Comment by e-orz** [comment]
@bryaakov I don't remember. We should ask @yanpom about it.
