### ISSUE TITLE
health monitor fails when using 1 cas with grid configuration

### ISSUE THREAD

**Issue by yanpom** [CM-Well/CM-Well#1186]
All cas are reds after installation
Following error appears in cas monitor actor log

2019-07-10 07:42:34,805 [scala-execution-context-global-77]          ERROR c.ctrl.server.CassandraMonitorActor  - Failed to check component
java.lang.ArrayIndexOutOfBoundsException: 1
        at cmwell.ctrl.checkers.CassandraChecker$.$anonfun$getCassandraStatus$1(CassandraChecker.scala:49)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
        at scala.collection.TraversableLike.map(TraversableLike.scala:237)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
        at cmwell.ctrl.checkers.CassandraChecker$.cmwell$ctrl$checkers$CassandraChecker$$getCassandraStatus(CassandraChecker.scala:47)
        at cmwell.ctrl.checkers.CassandraChecker$.$anonfun$check$2(CassandraChecker.scala:71)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by MoriaYechiel** [comment]
PR #1201
