### ISSUE TITLE
Latest Docker image not starting

### ISSUE THREAD

**Issue by nicklester** [CM-Well/CM-Well#1300]
6) Error injecting constructor, NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{AZFeCOk2QQKShSjDOprRBw}{127.0.0.1}{127.0.0.1:9301}]]
  at logic.CRUDServiceFS.<init>(CRUDServiceFS.scala:55)
  at logic.CRUDServiceFS.class(CRUDServiceFS.scala:55)
  while locating logic.CRUDServiceFS
    for the 1st parameter of security.EagerAuthCache.<init>(EagerAuthCache.scala:31)
  at security.EagerAuthCache.class(EagerAuthCache.scala:31)
  while locating security.EagerAuthCache
    for the 1st parameter of security.AuthUtils.<init>(AuthUtils.scala:30)
  while locating security.AuthUtils
    for the 1st parameter of controllers.BackPressureToggler.<init>(BackPressureToggler.scala:26)
  at controllers.BackPressureToggler.class(BackPressureToggler.scala:26)
  while locating controllers.BackPressureToggler
    for the 1st parameter of actions.ActiveInfotonGenerator.<init>(ActiveInfotonGenerator.scala:54)
  at actions.ActiveInfotonGenerator.class(ActiveInfotonGenerator.scala:53)
  while locating actions.ActiveInfotonGenerator
Caused by: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{AZFeCOk2QQKShSjDOprRBw}{127.0.0.1}{127.0.0.1:9301}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:352)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:248)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:57)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:394)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:396)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:385)
	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:679)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:45)
	at cmwell.fts.FTSService.<init>(FTSService.scala:109)
	at cmwell.fts.FTSService$.apply(FTSService.scala:70)
	at logic.CRUDServiceFS.<init>(CRUDServiceFS.scala:69)
	at logic.CRUDServiceFS$$FastClassByGuice$$f0851614.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)

**Comment by e-orz** [comment]
Hi,
Where did you take the image from?

**Comment by nicklester** [comment]
Hi @e-orz 
Latest image published to docker hub
Cheers!

**Comment by Ivan-Shestakov** [comment]
@nicklester this one [https://hub.docker.com/r/eorz/cm-well](url)? Updated about 2 months ago, and I've used it successfully.

**Comment by e-orz** [comment]
@nicklester There is no official image (yet). please paster you full docker run or pull.

Thanks!

**Comment by bryaakov** [comment]
@e-orz / @YuriiYarosh let's have an official Docker image for `pe`
