### ISSUE TITLE
STP - Connection pool causes agent to stop working

### ISSUE THREAD

**Issue by yanpom** [CM-Well/CM-Well#785]
Started oafull on EGL2
After 2 hours of normal work, connection pool errors started to appear constantly. See below the error
The number of such errors is huge
567135 times in couple of days - it overloads the log
After 2 days, errors stopped, and it seems that nothing happens and log is empty - agent is started but does nothing. Pausing and starting the agent, cause the connection pool errors to reappear immediately

```
2018-06-24 10:25:14,272 -well-egl2-akka.actor.default-dispatcher-57] ERROR cmwell.tools.data.utils.akka.Retry$  - [oafulloa-hierarchy] received failure
akka.stream.BufferOverflowException: Exceeded configured max-open-requests value of [128]. This means that the request queue of this pool (HostConnectionPoolSetup(cm-well-ppe.int.thomsonreuters.com,80,Connec
tionPoolSetup(ConnectionPoolSettings(20,0,5,128,1,30 seconds,ClientConnectionSettings(Some(User-Agent: cmwell-data-tools using akka-http/2.5.11),10 seconds,1 minute,512,None,<function0>,List(),ParserSettings
(2048,16,64,64,8192,64,377487360,256,1048576,Strict,RFC6265,true,Full,Error,Map(If-Range -> 0, If-Modified-Since -> 0, If-Unmodified-Since -> 0, default -> 12, Content-MD5 -> 0, Date -> 0, If-Match -> 0, If-
None-Match -> 0, User-Agent -> 32),false,true,akka.stream.impl.ConstantFun$$$Lambda$781/1202382533@698e6236,akka.stream.impl.ConstantFun$$$Lambda$781/1202382533@698e6236,akka.stream.impl.ConstantFun$$$Lambda
$782/1033220492@57067221),None),Legacy,1 second,TCPTransport),akka.http.scaladsl.HttpConnectionContext$@1a7e826a,akka.event.MarkerLoggingAdapter@1ec2770e))) has completely filled up because the pool currentl
y does not process requests fast enough to handle the incoming request load. Please retry the request later. See http://doc.akka.io/docs/akka-http/current/scala/http/client-side/pool-overflow.html for more i
nformation.
        at akka.http.impl.engine.client.PoolInterfaceActor.<init>(PoolInterfaceActor.scala:88)
        at akka.http.impl.engine.client.PoolInterfaceActor$.$anonfun$props$1(PoolInterfaceActor.scala:34)
        at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:87)
        at akka.actor.Props.newActor(Props.scala:213)
        at akka.actor.ActorCell.newActor(ActorCell.scala:626)
        at akka.actor.ActorCell.create(ActorCell.scala:652)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:525)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
        at akka.dispatch.Mailbox.run(Mailbox.scala:223)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

**Comment by nicklester** [comment]
Reset to use newHostConnectionPool

**Comment by yanpom** [comment]
Happened again on EGl2 - after 2 days of running of oa-full agent
```
2018-07-19 07:55:06,731 -well-egl2-akka.actor.default-dispatcher-52] WARN  cmwell.tools.data.utils.akka.Retry$  - [oafulloa-hierarchy] received 200 OK but response body is not valid. host=c727vbacsnd12.int.thomsonreuters.com data=/data.thomsonreuters.com/2-28df8098e9d480eaea0205d0c26224b7168e62407c6804c58109d08b9cdd4e0f
2018-07-19 07:55:08,435 -well-egl2-akka.actor.default-dispatcher-64] ERROR cmwell.tools.data.utils.akka.Retry$  - [oafulloa-identifiers] status is not success (500 Internal Server Error) HttpEntity.Strict(application/json,{"success":false,"error":"Exceeded configured max-open-requests value of [1024]. This means that the request queue of this pool (HostConnectionPoolSetup(localhost,9000,ConnectionPoolSetup(ConnectionPoolSettings(4,0,5,1024,1,30 seconds,ClientConnectionSettings(Some(User-Agent: akka-http/10.0.11),10 seconds,1 minute,512,None,<function0>,List(),ParserSettings(2048,16,64,64,8192,64,8388608,256,1048576,Strict,RFC6265,true,Full,Error,Map(If-Range -> 0, If-Modified-Since -> 0, If-Unmodified-Since -> 0, default -> 12, Content-MD5 -> 0, Date -> 0, If-Match -> 0, If-None-Match -> 0, User-Agent -> 32),false,true,akka.stream.impl.ConstantFun$$$Lambda$683/1215466851@14d6b113,akka.stream.impl.ConstantFun$$$Lambda$683/1215466851@14d6b113,akka.stream.impl.ConstantFun$$$Lambda$684/200596599@69b4a9a5),None),Legacy,1 second,TCPTransport),akka.http.scaladsl.HttpConnectionContext$@6161c4b1,akka.event.MarkerLoggingAdapter@25656b97))) has completely filled up because the pool currently does not process requests fast enough to handle the incoming request load. Please retry the request later. See http://doc.akka.io/docs/akka-http/current/scala/http/client-side/pool-overflow.html for more information."})
2018-07-19 07:55:08,435 -well-egl2-akka.actor.default-dispatcher-64] WARN  cmwell.tools.data.utils.akka.Retry$  - [oafulloa-identifiers] server error: will retry again in 30 seconds host=Some(X-CMWELL-Hostname: c525cqycsnd03.int.thomsonreuters.com) status=500 Internal Server Error entity=HttpEntity.Strict(application/json,{"success":false,"error":"Exceeded configured max-open-requests value of [1024]. This means that the request queue of this pool (HostConnectionPoolSetup(localhost,9000,ConnectionPoolSetup(ConnectionPoolSettings(4,0,5,1024,1,30 seconds,ClientConnectionSettings(Some(User-Agent: akka-http/10.0.11),10 seconds,1 minute,512,None,<function0>,List(),ParserSettings(2048,16,64,64,8192,64,8388608,256,1048576,Strict,RFC6265,true,Full,Error,Map(If-Range -> 0, If-Modified-Since -> 0, If-Unmodified-Since -> 0, default -> 12, Content-MD5 -> 0, Date -> 0, If-Match -> 0, If-None-Match -> 0, User-Agent -> 32),false,true,akka.stream.impl.ConstantFun$$$Lambda$683/1215466851@14d6b113,akka.stream.impl.ConstantFun$$$Lambda$683/1215466851@14d6b113,akka.stream.impl.ConstantFun$$$Lambda$684/200596599@69b4a9a5),None),Legacy,1 second,TCPTransport),akka.http.scaladsl.HttpConnectionContext$@6161c4b1,akka.event.MarkerLoggingAdapter@25656b97))) has completely filled up because the pool currently does not process requests fast enough to handle the incoming request load. Please retry the request later. See http://doc.akka.io/docs/akka-http/current/scala/http/client-side/pool-overflow.html for more information."})
2018-07-19 07:55:09,684 [scala-execution-context-global-410]         ERROR cmwell.tools.data.utils.akka.Retry$  - [oafulloa-identifiers] error in consuming data bytes from response, paths=/data.thomsonreuters.com/2-2303727a17ea66957e6ae87aac071dd26311e8dfaa5c88b6698e1c099508bb8c, err=akka.http.scaladsl.model.EntityStreamException: Entity stream truncation
akka.http.scaladsl.model.EntityStreamException: Entity stream truncation
```
