### ISSUE TITLE
Crawler is stuck when encounteres plus one ms case

### ISSUE THREAD

**Issue by Ivan-Shestakov** [CM-Well/CM-Well#981]
On specific environment we see that crawler is constantly restarted on  3 partitions. This error gets printed repeatedly in the crawler.log
CM-Well version d1588f137b8627c6358c06fd72e0b47b79a59a40
```
ERROR cmwell.crawler.CrawlerStream$        - Crawler [persist_topic, partition: 1]: The stream exited with an exception. If the system is up│

│java.lang.IllegalArgumentException: Invalid format: "1541702537397" is malformed at "7397"                                                                                                                       │

│       at org.joda.time.format.DateTimeParserBucket.doParseMillis(DateTimeParserBucket.java:187)                                                                                                                 │

│       at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:826)                                                                                                                         │

│       at org.joda.time.convert.StringConverter.getInstantMillis(StringConverter.java:65)                                                                                                                        │

│       at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:173)                                                                                                                                          │

│       at org.joda.time.DateTime.<init>(DateTime.java:257)                                                                                                                                                       │

│       at cmwell.crawler.CrawlerStream$.$anonfun$createAndRunCrawlerStream$17(CrawlerStream.scala:164)                                                                                                           │

│       at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)                                                                                                                                           │

│       at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)                                                                                                                               │

│       at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)                                                                                                                                           │

│       at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)                                                                                                                   │

│       at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)                                                                                                                │

│       at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)                                                                                                                                 │

│       at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)                                                                                                                                 │

│       at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)                                                                                                                           │

│       at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)                                                                                                                                          │

│       at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)                                                                                                │

│       at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)                                                                                                                                      │

│       at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)                                                                                                                          │

│       at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)                                                                                                                                  │

└       at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by Ivan-Shestakov** [comment]
Validated on 1.5.163+21-63da9550 
Method: On pe environment ingest an infoton and  add  2 more versions.
Use kafka-simple-consumer.sh to get those messages.
Reinstall pe environment.
Inject the messages to kafka, reversing the order of the updates.
Review bg log. Find the "adding 1 milli" line. 
Review crawler log, validate it does not crash.

Closing this one and moving to Done.
